AWSTemplateFormatVersion: 2010-09-09
Description: Configure the AWSCloudFormationStackSetAdministrationRole and
  AWSCloudFormationStackSetExecutionRole to enable use of AWS CloudFormation StackSets in a single account.

Resources:
  AdministrationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AWSCloudFormationStackSetAdministrationRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: AssumeRole-AWSCloudFormationStackSetExecutionRole
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - sts:AssumeRole
                Resource:
                  - "arn:aws:iam::*:role/AWSCloudFormationStackSetExecutionRole"

  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AWSCloudFormationStackSetExecutionRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Ref "AWS::AccountId"
            Action:
              - sts:AssumeRole
      Path: /

  ExecutionRolePolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: StackSetMiningExecutionRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Resource: "*"
          Action:
          - cloudformation:*
          - s3:*
          - sns:*
          - ec2:DescribeImages
          - ec2:DescribeSubnets
          - ec2:RequestSpotInstances
          - ec2:RequestSpotFleet
          - ec2:TerminateInstances
          - ec2:DescribeInstanceStatus
          - ec2:DescribeSecurityGroups
          - ec2:CreateTags
          - ec2:CreateSecurityGroup
          - ec2:AuthorizeSecurityGroupIngress
          - iam:GetRole
          - iam:CreateRole
          - iam:PutRolePolicy
          # Allow stack to delete
          - ec2:DeleteSecurityGroup
          - iam:DeleteRole
          - iam:DeleteRolePolicy
      Roles:
      - !Ref ExecutionRole
